import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";

import { Navbar } from "@/components/navbar";
import { VerticalText } from "@/components/pages/vertical-text";

import { Routes } from "@/lib/constants";

const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const headersList = headers();
	const pathname = headersList.get("x-invoke-path");

	const routeName = Object.keys(Routes).find(
		(key) => pathname === Routes[key as keyof typeof Routes]
	);

	return (
		<html lang="en">
			<body className={leagueSpartan.className}>
				<Navbar />
				<VerticalText>{routeName}</VerticalText>
				<div className="relative lg:mt-14">{children}</div>
			</body>
		</html>
	);
}
