import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";

import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/pages/footer";
import { VerticalText } from "@/components/pages/vertical-text";
import { twMerge } from "tailwind-merge";

const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={twMerge([
					leagueSpartan.className,
					"flex flex-col min-h-[100dvh]",
				])}
			>
				<Navbar />
				<VerticalText />
				<div className="relative grow">{children}</div>
				<Footer />
			</body>
		</html>
	);
}
